assetic:
    assets:
        rtxbackbonebundle:
            inputs:
                - @RtxLabsBackboneBundle/Resources/public/js/json2.js
                - @RtxLabsBackboneBundle/Resources/public/js/underscore.js
                - @RtxLabsBackboneBundle/Resources/public/js/backbone.js
                - @RtxLabsBackboneBundle/Resources/public/js/extension/backbone.validations.js