assetic:
    assets:
        rtxbackbonebundle:
            inputs:
                - @RtxLabsBackboneBundle/Resources/public/js/json2.js
                - @RtxLabsBackboneBundle/Resources/public/js/underscore-min.js
                - @RtxLabsBackboneBundle/Resources/public/js/backbone-min.js